app: vjepa_droid # NOTE (VG): change if needed
cpus_per_task: 12
folder: /storage/home/hcoda1/6/vgiridhar6/scratch/vjepa2/090725
mem_per_gpu: 220G
nodes: 4
tasks_per_node: 8
data:
  batch_size: 8
  camera_views:
  - left_mp4_path
  crop_size: 256
  datasets:
    # CSV file, each line is a trajectory dir path
    # See https://github.com/facebookresearch/z/issues/65
    - /storage/home/hcoda1/6/vgiridhar6/r-agarg35-0/dinowm_data/datasets/pusht_noise/train
  dataset_fpcs:
  - 10
  fps: 4
  num_workers: 12
  patch_size: 16
  pin_mem: true
  stereo_view: true
  tubelet_size: 2
  frameskip: 5
data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 1.777
  - 1.777
  reprob: 0.0
loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
meta:
  dtype: bfloat16
  eval_freq: 100
  resume_checkpoint:
  load_predictor: false
  pretrain_checkpoint: /storage/home/hcoda1/6/vgiridhar6/r-agarg35-0/vjepa2/vjepa2-vitg-fpc64-256/original/model.pth
  context_encoder_key: target_encoder
  target_encoder_key: target_encoder
  save_every_freq: 5
  seed: 239
  use_sdpa: true
model:
  model_name: vit_giant_xformers
  pred_depth: 24
  pred_embed_dim: 1024
  pred_is_frame_causal: true
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true
  use_extrinsics: false
  use_rope: true
optimization:
  anneal: 15
  epochs: 315
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: 300
  lr: 0.000425
  start_lr: 0.000075
  warmup: 15
  weight_decay: 0.04
wandb:
  project: world_model_smoothness
  entity: pair-diffusion
  enable: true
  name: vjepa2_train_test_090725
  tags:
    - pusht
    - vjepa2
