_target_: planning.mpc.MPCPlanner
max_iter: null # unlimited if null
n_taken_actions: 5
sub_planner:
  target: planning.cem.CEMPlanner
  horizon: 5
  topk: 30
  num_samples: 300 #reduce ot 100
  var_scale: 1
  opt_steps: 30 #10 steps
  eval_every: 1

name: mpc_cem